jwt:
  secret: your-256-bit-secret-your-256-bit-secret

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
        - id: music-service
          uri: lb://music-service
          predicates:
            - Path=/api/music/**
        - id: route-service
          uri: lb://route-service
          predicates:
            - Path=/api/route/**

  security:
    oauth2:
      resourceserver:
        jwt:
          # ✅ Corrected: `secret-key` is part of Spring Security, not top-level
          secret-key: your-256-bit-secret-your-256-bit-secret

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-service:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: "*"
