spring:
  application:
    name: route-service

server:
  port: 8083

eureka:
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: ${SPRING_EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-service:8761/eureka/}

nominatim:
  url: https://nominatim.openstreetmap.org

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.web.client.RestTemplate: INFO
