spring:
  application:
    name: route-service

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: ${SPRING_EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-service:8761/eureka/}

nominatim:
  base-url: https://nominatim.openstreetmap.org
  endpoints:
    search: /search
    reverse: /reverse

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    org.springframework.web.client.RestTemplate: INFO
