version: '3.8'

services:
  config-service:
    container_name: config-service
    build: ./config-service
    ports:
      - "8888:8888"
    networks:
      - journey-network
    environment:
      - SERVER_PORT=8888
      - SPRING_APPLICATION_NAME=config-service
      - SPRING_EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8761/eureka/
    volumes:
      - ./config-repo:/config-repo

  eureka-service:
    container_name: eureka-service
    build: ./eureka-service
    ports:
      - "8761:8761"
    networks:
      - journey-network
    depends_on:
      - config-service
    environment:
      - SERVER_PORT=8761
      - SPRING_APPLICATION_NAME=eureka-service
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888

  gateway-service:
    build: ./gateway-service
    container_name: gateway-service
    ports:
      - "8080:8080"
    depends_on:
      config-service:
        condition: service_started
      eureka-service:
        condition: service_started
    environment:
      - SERVER_PORT=8080
      - SPRING_APPLICATION_NAME=gateway-service
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888
      - SPRING_EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8761/eureka/
    networks:
      - journey-network

  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - journey-network

  user-service:
    build: ./user-service
    container_name: user-service
    depends_on:
      user-db:
        condition: service_started
      config-service:
        condition: service_started
      eureka-service:
        condition: service_started
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SPRING_APPLICATION_NAME=user-service
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888
      - SPRING_EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8761/eureka/
    networks:
      - journey-network

  music-service:
    build: ./music-service
    container_name: music-service
    ports:
      - "8082:8082"
    depends_on:
      config-service:
        condition: service_started
      eureka-service:
        condition: service_started
    environment:
      - SERVER_PORT=8082
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-service:8888
      - SPRING_EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-service:8761/eureka/
      - SPOTIFY_CLIENT_ID=d9a786a96ea44f9bbfa5228457b11589
      - SPOTIFY_CLIENT_SECRET=1c7be3850109498f953b58e9cde315bc
    networks:
      - journey-network

networks:
  journey-network:
    driver: bridge
