spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://user-db:5432/users
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  config:
    import: optional:configserver:http://config-service:8888

eureka:
  client:
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
