spring:
  application:
    name: eureka-service

  config:
    import: optional:configserver:http://config-service:8888

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

  server:
    enable-self-preservation: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
